version: '3'

services:
  mariadb:
    build: ${PWD}/requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - the-net

  wordpress:
    depends_on: 
      - mariadb
    build: ${PWD}/requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    # ports:
    #   - 9000:9000
    networks:
      - the-net

  nginx:
    depends_on:
      - wordpress
    build: ${PWD}/requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - the-net

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/data/db
  
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/wp

networks:
  the-net:
    driver : bridge