version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ${PWD}/srcs/requirements/mariadb/
      args:
        - DB_NAME=mariadb
        - DB_USER=barae
        - DB_PASS=1234
        - DB_ROOT_PASS=1234
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - the-net
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    build: ${PWD}/srcs/requirements/bonus/redis/
    networks:
      - the-net
    restart: unless-stopped

  wordpress:
    depends_on: 
      - mariadb
    image: wordpress
    container_name: wordpress
    build:
      context: ${PWD}/srcs/requirements/wordpress/
      args:
        - DB_NAME=mariadb
        - DB_USER=barae
        - DB_PASS=1234
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - the-net
    restart: unless-stopped

  nginx:
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx
    build: ${PWD}/srcs/requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - the-net
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    build: ${PWD}/srcs/requirements/bonus/adminer
    networks:
      - the-net
    restart: unless-stopped

  static_page:
    image: static_page
    container_name: static_page
    build: ${PWD}/srcs/requirements/bonus/static_page
    networks:
      - the-net
    restart: unless-stopped

  ftp:
    image: ftp
    container_name: ftp
    build: ${PWD}/srcs/requirements/bonus/ftp
    environment:
      - FTP_USER=ftpu
      - FTP_PASS=1234
    ports:
      - "21:21"
      - 21100-21110:21100-21110
    networks:
      - the-net
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: unless-stopped
  
  portainer:
    image: portainer
    container_name: portainer
    build: ${PWD}/srcs/requirements/bonus/portainer
    ports:
      - 8000:8000
      - 9443:9443
    environment:
      - PASS=testtest1234
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    restart: unless-stopped

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/srcs/data/db
  
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/srcs/data/wp

  portainer:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/srcs/data/pr

networks:
  the-net:
    driver : bridge